### ISSUE TITLE
FTP upload failed

### ISSUE THREAD

**Issue by sebastian-tennant** [Cacti/plugin_gexport#10]
I have an issue with this plugin where uploading to an FTP site fails. I have confirmed I'm able to upload to this site with the credentials specified and from the same box, manually. 

I have debugging for the plugin turned on, however, not much information is returned. Is there any way of getting more information? Excerpt of log and proof below. I've also tried passive mode. 

```
2017-06-01 12:19:03 - EXPORT Using active transfer method.
2017-06-01 12:19:03 - EXPORT Using PHP built-in FTP functions.
2017-06-01 12:19:03 - EXPORT FATAL ERROR: FTP Connection failed! Check hostname and port.  Export can not continue.
```
![2](https://cloud.githubusercontent.com/assets/29113210/26664739/65ab40fe-46c6-11e7-9148-e962d6e8ce21.png)
![untitled](https://cloud.githubusercontent.com/assets/29113210/26664738/659c76be-46c6-11e7-9846-fedc5555ff3a.png)

**Comment by sebastian-tennant** [comment]
I have created a local FTP server and tried pointing an upload at that - cacti doesn't even connect to the server. 

I suspect this is an issue in my PHP configuration somewhere, but I'm unsure as to where

**Comment by cigamit** [comment]
Can you please run the poller_gexport.php in debug mode as follows and post results:

`php -q poller_gexport.php --id=N --debug --force`

Please grep out the RRDtool output and only capture the FTP output.

**Comment by cigamit** [comment]
I've tested with the latest Cacti and Gexport, and the FTP works find.  I'm unable to reproduce.
