### ISSUE TITLE
After upgrade to 1.1.9 exports cannot be rendered by browser

### ISSUE THREAD

**Issue by thowo** [Cacti/plugin_gexport#11]
Hello,

after upgrading  cacti  from 1.1.1 to 1.1.9 (and gexport latest from github) the graph export is running, pages will be generated and (s)copied to the remote system. So far so good,  but if I want to watch the exported graphs, nothing will be shown in the browser. The JS Tree is rendered but the links are unusable and nothing will be shown...
After employing firebug, I found the following error:
clearFilter is not defined

So it seems the issue is in relation to  the cacti issue #789
"Unable to clearFilter due to name space collision."

After all: when I comment out line 1095 in layout.js graphs are back again

function setupSpecialKeys() {
        // $('#filter, #rfilter').unbind('keypress').attr('title',clearSearchFilter);

Can anyone please fix it in the source repo?

thanks in advance, 
best regards, 
Tom

**Comment by cigamit** [comment]
This was resolved in Cacti 1.1.10, but please wait for Cacti 1.1.11 to be released early next week as there is a fairly significant bug in Cacti 1.1.10 that is resolved, but not released.
