### ISSUE TITLE
Call to undefined function gexport_version()

### ISSUE THREAD

**Issue by nelsonk** [Cacti/plugin_gexport#20]
Hello, i get below error when i put gexport folder into the plugins folder.

Fatal error: Call to undefined function gexport_version() in /path-to-cacti-folder/cacti/plugins.php on line 303

please advise.

**Comment by nelsonk** [comment]
Edited the plugins.php file to call plugin_gexport_version() instead and it worked.

**Comment by cigamit** [comment]
What version of Cacti?

**Comment by nelsonk** [comment]
Cacti Version: 0.8.8a, Plugin Architecture Version: 3.1

**Comment by cigamit** [comment]
That would explain it.  None of the plugins in this GitHub site are formally compatible with Cacti 0.8.x.  So, you will continue to have problems.

**Comment by nelsonk** [comment]
Am going to install a newer version of cacti, than you.
