### ISSUE TITLE
PHP Warning:  ftp_delete()

### ISSUE THREAD

**Issue by WirthmU** [Cacti/plugin_gexport#21]
I still have problem with running gexport.
When I do testing using "sudo php -q poller_export.php --id=1 --force --debug"

I get a lot of success but then also:

2017/10/03 21:43:34 - EXPORT Deleting Remote File 'images'
MEMUSE: 3 M, MESSAGE: Deleting Remote File 'images'
PHP Warning:  ftp_delete(): images: Is a directory in /var/www/cacti/plugins/gexport/functions.php on line 831
2017/10/03 21:43:34 - EXPORT Removing Remote Directory '/homepage/Bern/rpi01/js'
MEMUSE: 3 M, MESSAGE: Removing Remote Directory '/homepage/Bern/rpi01/js'
PHP Warning:  ftp_rmdir(): /homepage/Bern/rpi01/js: Directory not empty in /var/www/cacti/plugins/gexport/functions.php on line 837
2017/10/03 21:43:34 - EXPORT Deleting Remote File 'main.css'
MEMUSE: 3 M, MESSAGE: Deleting Remote File 'main.css'
2017/10/03 21:43:34 - EXPORT Deleting Remote File 'pace.css'
MEMUSE: 3 M, MESSAGE: Deleting Remote File 'pace.css'
2017/10/03 21:43:34 - EXPORT Deleting Remote File 'jquery-ui.css'
MEMUSE: 3 M, MESSAGE: Deleting Remote File 'jquery-ui.css'
2017/10/03 21:43:34 - EXPORT Deleting Remote File 'default'
MEMUSE: 3 M, MESSAGE: Deleting Remote File 'default'
PHP Warning:  ftp_delete(): default: Is a directory in /var/www/cacti/plugins/gexport/functions.php on line 831
2017/10/03 21:43:34 - EXPORT Deleting Remote File 'font-awesome.css'
MEMUSE: 3 M, MESSAGE: Deleting Remote File 'font-awesome.css'
2017/10/03 21:43:34 - EXPORT Deleting Remote File 'images'
MEMUSE: 3 M, MESSAGE: Deleting Remote File 'images'

It only works if before I delete all the remote directories except rpi01

Any help to this?

**Comment by cigamit** [comment]
Test again with the latest commit.

**Comment by cigamit** [comment]
No feedback.
