### ISSUE TITLE
.js & .css files?

### ISSUE THREAD

**Issue by cfishwick** [Cacti/plugin_gexport#29]
So whilst I love idea behind this plugin and have it installed and performing exports, the resulting index file is unusable as it includes calls to a whole lot of CSS and JS files that are not referenced anywhere else in the plugin.  Now, I know that most (all?) is included with various parts of Cacti etc, but that doesn't help with exporting to a different host etc.  Is there something I'm missing here?

**Comment by netniV** [comment]
No, you've hit the nail on the head.  The plugin is designed to generate a page where the CSS and JS are used to replicate the look and feel of your cacti installation.  If you have these copied over to another server, you can either parse the index.php output and create your own or copy over the static JS/CSS files and then the site will display the index page properly.

**Comment by cfishwick** [comment]
Unfortunately, packaging up the JS and CSS and copying it to another server/location doesn't work.  Looks pretty for the most part, but try and display and actual graph and it throws an error:

Uncaught ReferenceError: refreshPage is not defined
    at setGraphTabs (layout.js:909)
    at applySkin (layout.js:578)
    at renderGraphs ((index):350)
    at Object.success ((index):384)
    at fire (jquery.js:3268)
    at Object.fireWith [as resolveWith] (jquery.js:3398)
    at done (jquery.js:9305)
    at XMLHttpRequest.<anonymous> (jquery.js:9548)

Also, with regards to creating the JS & CSS file structure upon export, if "Clear DIrectory" is clicked, it appears to check if the directories exist, ready for an export, then deletes them all, then completes the export (minus most pretty much all the supporting files, because the directories were deleted).  Surely the correct order would be to, before anything else, clear the destination directory, *then* create the directory structure and then finally export/copy the files into that structure?

**Comment by netniV** [comment]
That should be what is happening, yes.  What makes you believe it's occurring the other way?  I haven't actually checked the source at this point to confirm and deny your findings.

**Comment by cfishwick** [comment]
Moving this chunk of code:
`        clearstatcache();`
`        if (!is_dir($export_path)) {`
`                if (!mkdir($export_path)) {`
`                        export_fatal($export, "Unable to create path '" . $export_path . "'!  Export can not continue.");`
`                }`
`        } else {`
`                if ($export['export_clear'] == 'on') {`
`                        delTree($export_path, true);`
`                }`
`        }`

from the "create_export_directory_structure" function to the "exporter" function in the functions.php file resolves this issue, but probably creates problems elsewhere, I haven't looked hard enough yet.

**Comment by netniV** [comment]
Feel free to create a PR if you can with your changes.  I'll review and commit if it looks right 👍 Alternatively, post your diff files here and I'll apply / commit them.

**Comment by netniV** [comment]
OK, I can see what you did there.  I think that should work OK.  Probably going to tweak it slightly more but thanks for the pointers 👍

**Comment by netniV** [comment]
So I went to have a quick look and apparently this isn't the latest version that is in the repository here.  Can you verify the version and source location you got your copy from?

**Comment by cfishwick** [comment]
Well that's weird, I did a git clone.  From the INFO file: 

[info]
name = gexport
version = 1.4.1
longname = Graph Export Package for Cacti
author = The Cacti Group
email =
homepage = http://www.cacti.net
compat = 1.1.10
capabilities = online_view:1, online_mgmt:1, offline_view:0, offline_mgmt:0, remote_collect:0

**Comment by netniV** [comment]
Does your functions.php mirror https://github.com/Cacti/plugin_gexport/blob/develop/functions.php

**Comment by cfishwick** [comment]
According to diff the git clone version and the one above are identical.

**Comment by netniV** [comment]
I’m confused by that then because line 416 in your diff was the one that was changed.  If that is the functions file that is part of the git clone, the online source doesn’t show code that matches before or after.

**Comment by dsclassen** [comment]
I'm not sure if this is related, but in the functions.php file there is a reference to a query-migrate.js file that does not exist in the cacti develop branch.
```
copy("$root_path/include/js/jquery-migrate.js", "$export_path/js/jquery-migrate.js");
```

**Comment by netniV** [comment]
As of Cacti Core 1.2, we do not utilise the the jquery-migrate any more.  But we haven't reviewed the plugins yet for 1.2 compatibility.  That will be coming shortly.

**Comment by netniV** [comment]
I've made an update to try and make more compatible with 1.2.  See if that helps you.
