### ISSUE TITLE
[1.2.0] Plugin is active but I didn't find how to define graphs to be exported

### ISSUE THREAD

**Issue by jackouille-ch** [Cacti/plugin_gexport#32]
![image](https://user-images.githubusercontent.com/35721406/44087662-db598c76-9fc0-11e8-971e-22ed1a8a6f81.png)
![image](https://user-images.githubusercontent.com/35721406/44088194-96356096-9fc2-11e8-8477-f79c72871d7b.png)

And I either didn't see anything within Graph Templates or Trees while editing them using the right clic

**Comment by netniV** [comment]
There is a separate menu option on the Console Navigation menu.

**Comment by jackouille-ch** [comment]
Where ?
![image](https://user-images.githubusercontent.com/35721406/44089595-a96f8722-9fc7-11e8-831e-9679edf0f69d.png)

**Comment by netniV** [comment]
Check you have the plugin enabled and that you have access rights to it under either user or group permissions.

**Comment by jackouille-ch** [comment]
Didn't see it:
![image](https://user-images.githubusercontent.com/35721406/44097234-985a132e-9fdd-11e8-9797-de1b981e069a.png)

**Comment by netniV** [comment]
Really?? It's right there on your screenshot ;-) . This is like a game of Where's Wally ... Good news is, your permissions are correct as I can see it turned on.  And I can also see that the permissions have worked 👍
