### ISSUE TITLE
Please update for 1.1.12

### ISSUE THREAD

**Issue by godsyn** [Cacti/plugin_gexport#33]
Please update for 1.1.12

**Comment by netniV** [comment]
Please explain what you mean.

**Comment by godsyn** [comment]
Current version throws a few errors when used in conjunction with 1.1.12.
For example : font-awesome.css is now fontawesome.css, but is referred to as its old filename, and throws errors.

**Comment by netniV** [comment]
font-awesome.css only lost the hyphen when 1.2 came out. 1.1.12 was hyphenated.

```
$ git checkout release/1.1.12
Checking out files: 100% (1855/1855), done.
Previous HEAD position was fe92e877 Merging for release v1.2.1
HEAD is now at 0558f917 Merge branch 'develop' for 1.1.12 release
$ cd include/fa/css
$ ls -1
font-awesome.css
font-awesome.css.map
font-awesome.min.css
index.php
```
