### ISSUE TITLE
Empty site variable may cause errors to appear

### ISSUE THREAD

**Issue by carboxste** [Cacti/plugin_gexport#37]
Hi to All,
after updating the cacti from 1.2.3 to 1.2.4 the gexport plugins no more work.

I tried to remove and enable it again but without success but the log shows only those informations:

cacti.log.3.gz:2019/07/10 05:18:27 - CMDPHP SQL Backtrace: (/plugins/gexport/poller_export.php[107]:graph_export(), /plugins/gexport/functions.php[120]:run_export(), /plugins/gexport/functions.php[162]:exporter(), /plugins/gexport/functions.php[421]:export_graphs(), /plugins/gexport/functions.php[747]:db_fetch_cell(), /lib/database.php[358]:db_fetch_cell_prepared(), /lib/database.php[374]:db_execute_prepared())

cacti.log.3.gz:2019/07/10 05:25:28 - CMDPHP SQL Backtrace: (/plugins/gexport/poller_export.php[107]:graph_export(), /plugins/gexport/functions.php[120]:run_export(), /plugins/gexport/functions.php[162]:exporter(), /plugins/gexport/functions.php[421]:export_graphs(), /plugins/gexport/functions.php[747]:db_fetch_cell(), /lib/database.php[358]:db_fetch_cell_prepared(), /lib/database.php[374]:db_execute_prepared())

The cacti forum suggested me to open an issue with Github

......
gexport likely uses a function that now has been changed to a byref parameter... can you open this is a bug on github for gexport repo?

_________________
Official Cacti Developer
.......

Could you please patch gexport for the last Cacti version?

Thanks a lot

Best regards

**Comment by carboxste** [comment]
???

**Comment by carboxste** [comment]
Understood, I will keep cacti 1.2.3 ang Gexport 1.4.2...

**Comment by netniV** [comment]
This should now be resolved.

**Comment by netniV** [comment]
Sorry, you were faster than me as my kids wanted a kiss goodnight between me pushing the update and commenting on here.

**Comment by carboxste** [comment]
Ah ok 
I am very sorry, I have misunderstood the reply :-D
Thanks a lot and good night to all :-D

**Comment by carboxste** [comment]
The problem persist. No prob we keep cacti version 1.2.3

**Comment by netniV** [comment]
Do you have the logs around this when the error reoccurred? Not just the SQL lines?

**Comment by carboxste** [comment]
Hello 
I have only the screenshot of cacti of error log.  If you tell me what have I to search, please leti me know.


Thank you
Best regards
Stefano




Stefano Carbonera
______________
INRETE S.r.l. 
Via Postiglione 29
10024 Moncalieri - TO 
Tel: +390116811590 
Fax: +390116811603 
e-mail: carbo@inrete.eu 
http://www.inrete.eu

**Comment by netniV** [comment]
Copy and paste the lines around the error, there is usually more than just the above since there is normally the actual SQL error.
