### ISSUE TITLE
Cacti Log Warning

### ISSUE THREAD

**Issue by WirthmU** [Cacti/plugin_gexport#44]
Gexport is working well.
However I get the following warning in the cacti log:
`WARNING: Attempt to set user setting 'sess_allowed_templates_lastchange', with no user id: (/plugins/gexport/poller_export.php[107]:graph_export(), /plugins/gexport/functions.php[120]:run_export(), /plugins/gexport/functions.php[181]:exporter(), /plugins/gexport/functions.php[422]:tree_site_export(), /plugins/gexport/functions.php[1907]:export_generate_site_html(), /plugins/gexport/functions.php[1625]:is_device_allowed(), /lib/auth.php[577]:get_allowed_devices(), /lib/auth.php[1851]:get_cached_allowed_type(), /lib/auth.php[1425]:set_user_setting())`

**Comment by TheWitness** [comment]
This is resolved now.

**Comment by godsyn** [comment]
Sill have this issue. 
Cacti 1.2.15
latest "release"(1.4.2) and last commit (2.0)

`WARNING: Attempt to set user setting 'sess_allowed_templates_lastchange', with no user id: (/plugins/gexport/poller_export.php[107]:graph_export(), /plugins/gexport/functions.php[120]:run_export(), /plugins/gexport/functions.php[162]:exporter(), /plugins/gexport/functions.php[422]:tree_site_export(), /plugins/gexport/functions.php[1921]:export_generate_site_html(), /plugins/gexport/functions.php[1639]:is_device_allowed(), /lib/auth.php[577]:get_allowed_devices(), /lib/auth.php[1855]:get_cached_allowed_type(), /lib/auth.php[1429]:set_user_setting()) `

**Comment by netniV** [comment]
@godsyn Make sure you have the latest develop version, it has not yet had a 2.0 tag for release.
