### ISSUE TITLE
Graphs not rendering on Cacti 1.2.15

### ISSUE THREAD

**Issue by MikeSierraRO** [Cacti/plugin_gexport#46]
This issue it's related to the initial one with number #3910.

@TheWitness solved the log error issue, but they are still not showing up on the website where they are beeing exported via FTP. The export works just fine, no error on the Log section, simply can't see the Graphs when selecting one device.

In the first screenshot it can be saw that when selected a device, no graphs are beeing showed up. Neither if I chose another one. Export runs at 5 minutes. 

In the second screenshot, it's the log that confirms the success of export over FTP.
![err1](https://user-images.githubusercontent.com/56639628/98481163-0ccceb80-2201-11eb-8f8d-b564ef8a1462.png)

![exportlog](https://user-images.githubusercontent.com/56639628/98481139-d000f480-2200-11eb-8b22-f5d9cc0559d2.png)

**Comment by TheWitness** [comment]
Okay, cool.  Now, open the Browsers debug panel (F12 on Windows, and goto the console there).  Then click on a host.  Do you see an error?  Second question, are the PNG files located on the server?

**Comment by RazvanZeces** [comment]
@TheWitness yup, it reports some errors.
![brerr](https://user-images.githubusercontent.com/56639628/98481201-5b7a8580-2201-11eb-8f8f-c2793daa3870.png)

Should I capture all errors?

**Comment by TheWitness** [comment]
Well, that's an interesting error.  I guess I have to install this thing to see what's going on.

**Comment by RazvanZeces** [comment]
It's weird because the PNG files are beeing exported and they are not corrupted or something else.

If I download them on my computer they show just fine. If I go to the root folder and access the graph_10.html file it shows just ok the graphs, but if I try to access them from the main website it's not working.

**Comment by RazvanZeces** [comment]
@TheWitness if you can give me an email address where I can contact you, I can give you access so you can have a look if it's easier for you.

**Comment by jav4** [comment]
Try changing, on line 267 of website.template from:

`...'.png').load(function() {`

to

`...'.png').on("load",function() {`

**Comment by TheWitness** [comment]
I've been looking at this most of the day.  Code was pretty wobbly.  Looks like there have been a bunch of Cacti changes, and this plugin has not been keeping up.  I'll have some updates shortly.

**Comment by TheWitness** [comment]
This should be fixed up now.

**Comment by MikeSierraRO** [comment]
It's working now.

Thank you for all the work @TheWitness
