### ISSUE TITLE
v2.0 installed, graphs exported, but not browsable

### ISSUE THREAD

**Issue by SproAdmin** [Cacti/plugin_gexport#48]
Hello,
I have cacti v1.2.16 installed on Ubuntu 20, just the default graphs, working fine. Then I installed the new plugin v2.0. The plugin does export all the graphs (I monitored this on my webspace), but when I browse the index.html located there, the browser shows 
![grafik](https://user-images.githubusercontent.com/77330674/104317839-d05a8c00-54de-11eb-8ef0-1eef4711b537.png)

"No Graphs found"
This is my Graph Export Definition:
![grafik](https://user-images.githubusercontent.com/77330674/104317741-a86b2880-54de-11eb-881e-447bc9810283.png)

Please give me any hint what do to. Thank you,
Volkmar

**Comment by TheWitness** [comment]
Bring up the browsers debug window and the go-to the console tab.  Check for JavaScript errors.  Though this seems like something else maybe.

**Comment by SproAdmin** [comment]
This the relevant output of BrowserConsole / Firefox after clearing browsers cache.
![grafik](https://user-images.githubusercontent.com/77330674/104425547-1a944980-5581-11eb-9b06-2de9f3f28407.png)

**Comment by thowo** [comment]
Hello,
your topic brought some remindings to my mind. I had the same issue and I could solve it by changing the website.template to the following:

 diff website.template website.template.org
12c12
<       <link href='css/font-awesome.css' type='text/css' rel='stylesheet'>
---
>       <link href='css/fontawesome.css' type='text/css' rel='stylesheet'>
265,266c265
<                                       //$('#graph_'+myGraphs[i]).attr('src', 'graphs/' + type + myGraphs[i] + '.png').load(function() {
<                                       $('#graph_'+myGraphs[i]).attr('src', 'graphs/' + type + myGraphs[i] + '.png').on('load', function() {
---
>                                       $('#graph_'+myGraphs[i]).attr('src', 'graphs/' + type + myGraphs[i] + '.png').load(function() {


hope it helps,
best regards,
cheers,

Tom

**Comment by SproAdmin** [comment]
Hi Tom, thanx, it seems you have a different version of gexport - I could not find the above strings within the file website.template.
I run the latest (developer) version v2.0 of gexport-plugin as it should be compatible to cacti 1.2.15/16.
cheers and regards, Volkmar

**Comment by thowo** [comment]
Hi Volkmar,
ok understood, so one more shoot in the dark: have you tried running your export with the cacti classic theme?
cheers again, Tom

**Comment by SproAdmin** [comment]
Hi everyone,
although the problem persists, I created new devices and graphs and found out, all the graphs created AFTER the installation of gexport are exported properly, including thumbmnails and links, graphs existing before gexport installation are not within the exported tree. So I can live with this issue, cause I don't need the cacti default graphs.
![grafik](https://user-images.githubusercontent.com/77330674/104815862-a4f5db00-5817-11eb-8360-1a67020248b5.png)
thanks to all who commented here. Regards, Volkmar

**Comment by ivancolqueetn** [comment]
hello someone knows how I can install gexport in windows 10.

for the moment I copy the files to the cacti folder in htdocs even so I get that error shown in the image
error: plugin directory is not correct. should be 'gexport' but is '..'

![image](https://user-images.githubusercontent.com/77028322/106170133-8de3b100-6166-11eb-8030-c9a27d132892.png)

**Comment by ivancolqueetn** [comment]
I am trying to put my graphics on a web page so that they are updated by day, week, month and year, if someone knows how to do it, can you please help

**Comment by netniV** [comment]
@ivancolqueetn your issue is that you must remove "plugin_" from the front of gexport once it is in the plugin directory.  You should also have logged that as a separate issue.
