### ISSUE TITLE
 I CANNOT SEE THE GRAPHICS BY LOCAL METHOD

### ISSUE THREAD

**Issue by ivancolqueetn** [Cacti/plugin_gexport#49]
this is my config

![image](https://user-images.githubusercontent.com/77028322/106371931-e8386980-6340-11eb-84ff-a90911d8eb16.png)

I only see this

![image](https://user-images.githubusercontent.com/77028322/106371942-0aca8280-6341-11eb-8f58-9b9666fd28bb.png)

i am using windows 10 pro

**Comment by TheWitness** [comment]
Look for JavaScript errors.

**Comment by ivancolqueetn** [comment]
![ERROR JAVA](https://user-images.githubusercontent.com/77028322/106533589-d97cbe80-64c8-11eb-8934-844f60d2cb02.png)

**Comment by TheWitness** [comment]
Google that.

**Comment by cigamit** [comment]
You are attempting to Open the files directly (FILE:// is not allowed by CORS).  They should be hosted by a webserver instead and viewed just like any other website.

**Comment by ivancolqueetn** [comment]
sorry, i'm new to this.

They have a tutorial on how to implement it on a web server and how to configure the graph export in cacti,

I already have a web server and a test web page

**Comment by TheWitness** [comment]
Let's move this discussion to the forums.
