### ISSUE TITLE
log file

### ISSUE THREAD

**Issue by WirthmU** [Cacti/plugin_gexport#5]
I added gexport to cacti version 1.1.2.

Unfortunately it does not export anything altough I used the same settings as versions of cacti where export was integrated.
I checked export logging in cacti - however there is nothing about exporting in the cacti.log file.

Is there a way gexport can be logged?

**Comment by cigamit** [comment]
There is not nearly enough information here to make any assessment of what your problem might be.

**Comment by WirthmU** [comment]
I would like to provide more information - this is why I was looking for a log file, but cacti.log doesn't state anything about gexport. In the status line of gexport in cacti it's just stating "failed".

**Comment by cigamit** [comment]
You can run gexport from the command line using the --debug & --force options to find the issue.  It's likely a permissions or tools issue.  Make sure you use the crontab's user account.  Here is an example:

`php -q poller_export.php --id=1 --force --debug`

**Comment by WirthmU** [comment]
Export creating graphs and files works fine. I get an error upon ftp uploading. My user ID on the ftp site is 29 characters long. I noticed that I was unable to enter it in the plugin. Is there a limit of size?

**Comment by cigamit** [comment]
It was 20.  Just updated to 1.1 where the limit is now 40.
