### ISSUE TITLE
PNG not readable

### ISSUE THREAD

**Issue by rightvision** [Cacti/plugin_gexport#55]
**Describe the bug**
Incomplete or wrong png format. Images not readable by browser/windows...

**Screenshots**
see below sampe png file

**Plugin (please complete the following information):**
Monitor	Device Monitoring	Aktiv	The Cacti Group	2.5	
Gexport	Graph Export Package for Cacti	Aktiv	The Cacti Group		2.0	
Intropage	Intropage/Dashboard	Aktiv	The Cacti Group, Petr Macek		4.0.2	
Quicktree	QuickTree for Cacti	Aktiv	Howard Jones		2.0	
Reportit	Reporting tool for Cacti	Aktiv	The Cacti Group		1.1.3	
Syslog	Syslog Monitoring	Nicht installiert	The Cacti Group		4.0	
Thold	Thresholds	Aktiv	The Cacti Group		1.6	
Wmi	WMI Information Collector	Aktiv	The Cacti Group		1.0	

**Server**
Debian 11, Apache2, PHP8.1 (tested also with 7.4)

**Desktop (please complete the following information):**
 - all browsers latest versions

**Additional context**
![graph_17_3](https://user-images.githubusercontent.com/6069253/205275358-0af59701-31bd-41c5-917a-51f9e736f962.png)

**Comment by TheWitness** [comment]
You might want to upload the file.

**Comment by TheWitness** [comment]
stet that, you did :)

**Comment by TheWitness** [comment]
Interesting.  That is not a PNG, that is SVG.

**Comment by TheWitness** [comment]
I have not used this plugin in a while.  Let me see what is going on.

**Comment by TheWitness** [comment]
Okay, confirmed everything is fine now.
