### ISSUE TITLE
Mkdir permission denied in file

### ISSUE THREAD

**Issue by Anonymou567** [Cacti/plugin_gexport#56]
Good day,

I have installed and enabled gexport in my cacti but when I tried to test it out, I get a permission denied for mkdir in functions.php on line 1956. May I know what files need which permissions for it to work? Image below shows the error, thank you.

![image](https://user-images.githubusercontent.com/101535103/217691406-e21c0025-fc23-4341-a0cf-8f2f84a03b33.png)

**Comment by netniV** [comment]
The error suggests that you haven't specified a directory for the export.  if you have, that directory does not have full permissions to create folders and files for either cron or the webserver user (apache, www-data, etc).

**Comment by Anonymou567** [comment]
Hi netniV, thanks for the help, I changed the directory owner to apache:apache. Its working now.
