### ISSUE TITLE
CMDPHP PHP ERROR WARNING

### ISSUE THREAD

**Issue by WirthmU** [Cacti/plugin_gexport#57]
**Describe the bug**
 CMDPHP PHP ERROR WARNING in cacti log file complaining about 

**To Reproduce**
```
 28-02-2023 13:30:10 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/gexport/poller_export.php[99]:graph_export(), /plugins/gexport/functions.php[120]:run_export(), /plugins/gexport/functions.php[186]:export_ftp_php_execute(), /plugins/gexport/functions.php[1133]:export_ftp_php_uploaddir(), /plugins/gexport/functions.php[1191]:export_ftp_php_uploaddir(), /plugins/gexport/functions.php[1187]:ftp_mkdir(), CactiErrorHandler())
28-02-2023 13:30:10 - ERROR PHP WARNING in Plugin 'gexport': ftp_mkdir(): images: File exists. in file: /usr/share/cacti/site/plugins/gexport/functions.php on line: 1187 
```

**Expected behavior**
no gexport error in cacti log

**Screenshots**

**Plugin (please complete the following information):**
 - Version: latest
 - Source:  github
 - Identifer: [e.g. apt/yum package name or github commit ref]

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox

**Smartphone (please complete the following information):**

**Additional context**

**Comment by TheWitness** [comment]
You need to enable the sensitization of the remote directory if you wish to ignore this error at the current time.  It's not quite a bug per-se.  It's a downside of using the FTP method.

**Comment by TheWitness** [comment]
![image](https://user-images.githubusercontent.com/1439914/223300576-fa8dd7fc-b605-43a8-8843-a79c26972dc9.png)

**Comment by TheWitness** [comment]
I pushed an update to functions.php.  Update it and before you enable sensitization, see if it fixes it.

**Comment by WirthmU** [comment]
The updated functions.php did the trick - no more warnings.

Thank you

**Comment by TheWitness** [comment]
Cool!
