### ISSUE TITLE
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported

### ISSUE THREAD

**Issue by TheMetMan** [Cacti/plugin_gexport#60]
**Describe the bug**
I can enable the Plugin, but get this error when I go to Utilities - Graph Exports
Full Error:
```
[proxy_fcgi:error] [pid 1324] [client 10.6.10.10:46284] AH01071: Got error 'PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/cacti-1.2.25/plugins/gexport/gexport.php on line 247', referer: http://pi64-eumetcast.fsoft.nnet/cacti/utilities.php?action=view_logfile
```

**To Reproduce**
Enable the Plugin and go to the Utilities - Graph Exports Page
I get this: 500 Internal Server Error

**Expected behavior**
Should display the Graph Exoprts to configure

**Plugin (please complete the following information):**
 - Version: [ 2.1]
 - Source: [github]

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04 for Raspberry PI 4]
 - Cacti Version 1.2.25 official download
 - PHP version 8.2

How can I fix this?

**Comment by TheWitness** [comment]
Old and duplicate issue.  Update to the latest develop branch.

**Comment by TheMetMan** [comment]
Very sorry, my error, I had installed a previous version without realising it.
